{% set name = "clans" %}
{% set version = "v2.0.1_beta" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_tag: v2.0.1_beta
  url: https://github.com/inbalpaz/CLANS/releases/download/{{ version }}/CLANS_{{ version }}.tar.gz
  sha256: 1a7040db9b11d53b81be301141c5fff942d5c82d1da86379a2d223f7cede3d6e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python=3.9
    - numpy=1.20
    - pip
  run:
    - python=3.9
    - {{ pin_compatible('numpy') }}
    - numba=0.53.1
    - vispy=0.8.1
    - pyqt=5.9.2
    - biopython=1.77
    - pillow=8.3.1
    - blast

test:
  imports:
    - clans
    - clans.config
    - clans.io
    - clans.GUI
    - clans.data
    - clans.graphics
    - clans.layouts
    - clans.similarity_search
    - clans.taxonomy
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/inbalpaz/CLANS
  description: |
    CLANS is a Python-based program for visualizing the relationship between proteins 
    based on their pairwise sequence similarities. 
    The program implements a version of the Fruchterman-Reingold 
    force directed graph layout algorithm to visualize the sequence similarities in a 2D or 3D space.
  license: GPL
  license_family: GPL
  license_file: LICENSE.txt
  doc_url: https://github.com/inbalpaz/CLANS/tree/master/manual/Manual.pdf

